theme: jekyll-theme-minimal
title: Ziqi Yin's homepage
logo: /assets/img/Photo_Ziqi.jpg
description: Bookmark this to keep an eye on my project updates!
navbar:
  title: "My Website"
  left:
  - text: "Contact"
    href: Contact.md
include: README.md
