theme: jekyll-theme-minimal
title: Ziqi Yin
logo: /assets/img/Photo_Ziqi_Boulder.jpg
#description: Hi! I am a PhD student at University of Colorado, Boulder, studying about ice sheet-climate interactions.
show_downloads: False

#navbar:
#  title: "My Website"
#  left:
#  - text: "Contact"
#    href: Contact.md
#include: README.md
